version: '2'
services:
  zookeeper:
    image: eventuateio/eventuateio-local-zookeeper:0.20.1.RELEASE
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888


  kafka:
    image: eventuateio/eventuateio-local-kafka:0.20.1.RELEASE
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
      - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
      - ZOOKEEPER_SERVERS=zookeeper:2181

  postgres:
    build: ./postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: uploadservice
      POSTGRES_PASSWORD: uploadservice

  cdcservice:
    image: eventuateio/eventuate-tram-cdc-mysql-service:0.9.0.RELEASE
    ports:
      - "8099:8080"
    depends_on:
      - postgres
      - kafka
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/uploadservice
      SPRING_DATASOURCE_USERNAME: uploadservice
      SPRING_DATASOURCE_PASSWORD: uploadservice
      SPRING_DATASOURCE_TEST_ON_BORROW: "true"
      SPRING_DATASOURCE_VALIDATION_QUERY: SELECT 1
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_DB_USER_NAME: uploadservice
      EVENTUATELOCAL_CDC_DB_PASSWORD: uploadservice
      EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID: 1234567890
      EVENTUATELOCAL_CDC_SOURCE_TABLE_NAME: message
      SPRING_PROFILES_ACTIVE: EventuatePolling
